channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - numpy==1.26.0
  - pandas==2.1.3
  - psutil==5.9.0
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - xgboost==2.0.3
name: mlflow-env
